=begin
#Dyspatch API

## Introduction  The Dyspatch API is based on the REST paradigm and features resource based URLs with standard HTTP response codes to indicate errors. We use standard HTTP authentication and request verbs and all responses are JSON formatted. See our [Implementation Guide](https://docs.dyspatch.io/development/implementing_dyspatch/) for more details on how to implement Dyspatch.  ## API Client Libraries  Dyspatch provides API Clients for the following languages and web frameworks:  - [Java](https://github.com/getdyspatch/dyspatch-java) - [Javascript](https://github.com/getdyspatch/dyspatch-javascript) - [Python](https://github.com/getdyspatch/dyspatch-python) - [C#](https://github.com/getdyspatch/dyspatch-dotnet) - [Go](https://github.com/getdyspatch/dyspatch-golang) - [Ruby](https://github.com/getdyspatch/dyspatch-ruby) 

OpenAPI spec version: 2019.10
Contact: support@dyspatch.io
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.9

=end

# Common files
require 'dyspatch_client/api_client'
require 'dyspatch_client/api_error'
require 'dyspatch_client/version'
require 'dyspatch_client/configuration'

# Models
require 'dyspatch_client/models/api_error'
require 'dyspatch_client/models/body'
require 'dyspatch_client/models/body_1'
require 'dyspatch_client/models/compiled_read'
require 'dyspatch_client/models/created_at'
require 'dyspatch_client/models/cursor'
require 'dyspatch_client/models/draft_description'
require 'dyspatch_client/models/draft_id'
require 'dyspatch_client/models/draft_meta_read'
require 'dyspatch_client/models/draft_name'
require 'dyspatch_client/models/draft_read'
require 'dyspatch_client/models/draft_url'
require 'dyspatch_client/models/drafts_read'
require 'dyspatch_client/models/language_id'
require 'dyspatch_client/models/localization_id'
require 'dyspatch_client/models/localization_key_read'
require 'dyspatch_client/models/localization_meta_read'
require 'dyspatch_client/models/localization_name'
require 'dyspatch_client/models/localization_read'
require 'dyspatch_client/models/localization_url'
require 'dyspatch_client/models/template_description'
require 'dyspatch_client/models/template_id'
require 'dyspatch_client/models/template_meta_read'
require 'dyspatch_client/models/template_name'
require 'dyspatch_client/models/template_read'
require 'dyspatch_client/models/template_url'
require 'dyspatch_client/models/templates_read'
require 'dyspatch_client/models/updated_at'

# APIs
require 'dyspatch_client/api/drafts_api'
require 'dyspatch_client/api/localizations_api'
require 'dyspatch_client/api/templates_api'

module DyspatchClient
  class << self
    # Customize default settings for the SDK using block.
    #   DyspatchClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
