=begin
#Dyspatch API

## Introduction  The Dyspatch API is based on the REST paradigm, and features resource based URLs with standard HTTP response codes to indicate errors. We use standard HTTP authentication and request verbs, and all responses are JSON formatted. See our [Implementation Guide](https://docs.dyspatch.io/development/implementing_dyspatch/) for more details on how to implement Dyspatch.  ## API Client Libraries Dyspatch provides API Clients for popular languages and web frameworks.  - [Java](https://github.com/getdyspatch/dyspatch-java) - [Javascript](https://github.com/getdyspatch/dyspatch-javascript) - [Python](https://github.com/getdyspatch/dyspatch-python) - [C#](https://github.com/getdyspatch/dyspatch-dotnet) - [Go](https://github.com/getdyspatch/dyspatch-golang) - [Ruby](https://github.com/getdyspatch/dyspatch-ruby) 

The version of the OpenAPI document: 2020.04
Contact: support@dyspatch.io
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

# Common files
require 'dyspatch_client/api_client'
require 'dyspatch_client/api_error'
require 'dyspatch_client/version'
require 'dyspatch_client/configuration'

# Models
require 'dyspatch_client/models/api_error'
require 'dyspatch_client/models/compiled_read'
require 'dyspatch_client/models/cursor'
require 'dyspatch_client/models/draft_meta_read'
require 'dyspatch_client/models/draft_read'
require 'dyspatch_client/models/drafts_read'
require 'dyspatch_client/models/inline_object'
require 'dyspatch_client/models/localization_key_read'
require 'dyspatch_client/models/localization_meta_read'
require 'dyspatch_client/models/localization_read'
require 'dyspatch_client/models/template_meta_read'
require 'dyspatch_client/models/template_read'
require 'dyspatch_client/models/templates_read'

# APIs
require 'dyspatch_client/api/drafts_api'
require 'dyspatch_client/api/localizations_api'
require 'dyspatch_client/api/templates_api'

module DyspatchClient
  class << self
    # Customize default settings for the SDK using block.
    #   DyspatchClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
